services:
  zentra-user-service-postgres:
    container_name: zentra-user-service-postgres
    image: postgres:16.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: zentra-user-service-postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./docs/database/postgresql/postgresql.conf
        target: /etc/postgresql/postgresql.conf
      - type: bind
        source: ./docs/database/postgresql/pg_hba.conf
        target: /etc/postgresql/pg_hba.conf
    networks:
      - zentra-network
      - zentra-user-service-network
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    restart: on-failure

  zentra-user-service-redis-node-1:
    container_name: zentra-user-service-redis-node-1
    image: redis:7.2.2
    ports:
      - 5371:6379
      - 15371:16379
    volumes:
      - type: bind
        source: ./docs/database/redis/redis-node-1.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-user-service-redis-data-node-1
        target: /data
    networks:
      zentra-user-service-redis-network:
        ipv4_address: 172.48.0.11
      zentra-user-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure
  zentra-user-service-redis-node-2:
    container_name: zentra-user-service-redis-node-2
    image: redis:7.2.2
    ports:
      - 5372:6379
      - 15372:16379
    volumes:
      - type: bind
        source: ./docs/database/redis/redis-node-2.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-user-service-redis-data-node-2
        target: /data
    networks:
      zentra-user-service-redis-network:
        ipv4_address: 172.48.0.12
      zentra-user-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-user-service-redis-node-3:
    container_name: zentra-user-service-redis-node-3
    image: redis:7.2.2
    ports:
      - 5373:6379
      - 15373:16379
    volumes:
      - type: bind
        source: ./docs/database/redis/redis-node-3.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-user-service-redis-data-node-3
        target: /data
    networks:
      zentra-user-service-redis-network:
        ipv4_address: 172.48.0.13
      zentra-user-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-user-service-redis-node-4:
    container_name: zentra-user-service-redis-node-4
    image: redis:7.2.2
    ports:
      - 5374:6379
      - 15374:16379
    volumes:
      - type: bind
        source: ./docs/database/redis/redis-node-4.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-user-service-redis-data-node-4
        target: /data
    networks:
      zentra-user-service-redis-network:
        ipv4_address: 172.48.0.14
      zentra-user-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-user-service-redis-node-5:
    container_name: zentra-user-service-redis-node-5
    image: redis:7.2.2
    ports:
      - 5375:6379
      - 15375:16379
    volumes:
      - type: bind
        source: ./docs/database/redis/redis-node-5.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-user-service-redis-data-node-5
        target: /data
    networks:
      zentra-user-service-redis-network:
        ipv4_address: 172.48.0.15
      zentra-user-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-user-service-redis-node-6:
    container_name: zentra-user-service-redis-node-6
    image: redis:7.2.2
    ports:
      - 5376:6379
      - 15376:16379
    volumes:
      - type: bind
        source: ./docs/database/redis/redis-node-6.conf
        target: /usr/local/etc/redis/redis.conf
      - type: volume
        source: zentra-user-service-redis-data-node-6
        target: /data
    networks:
      zentra-user-service-redis-network:
        ipv4_address: 172.48.0.16
      zentra-user-service-network:
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: on-failure

  zentra-user-service-redisinsight:
    container_name: zentra-user-service-redisinsight
    image: redislabs/redisinsight:2.50
    ports:
      - 5541:5540
    networks:
      - zentra-user-service-redis-network

  zentra-user-service:
    image: zentra-user-service:latest
    container_name: zentra-user-service
    ports:
      - "3400:3400"
      - "4400:4400"
    networks:
      - zentra-network
      - zentra-user-service-network
      - zentra-user-service-redis-network
    depends_on:
      - zentra-user-service-postgres
      - zentra-user-service-redis-node-1
      - zentra-user-service-redis-node-2
      - zentra-user-service-redis-node-3
      - zentra-user-service-redis-node-4
      - zentra-user-service-redis-node-5
      - zentra-user-service-redis-node-6
    environment:
      - ZENTRA_APP_STATUS=DEVELOPMENT
      - ZENTRA_USER_SERVICE_WORKSPACE=/app/workspace
    volumes:
      - ./workspace:/app/workspace
      - ./tmp:/app/workspace/tmp
    restart: on-failure

volumes:
  zentra-user-service-postgres-data:
    name: zentra-user-service-postgres-data
  zentra-user-service-redis-data-node-1:
    name: zentra-user-service-redis-data-node-1
  zentra-user-service-redis-data-node-2:
    name: zentra-user-service-redis-data-node-2
  zentra-user-service-redis-data-node-3:
    name: zentra-user-service-redis-data-node-3
  zentra-user-service-redis-data-node-4:
    name: zentra-user-service-redis-data-node-4
  zentra-user-service-redis-data-node-5:
    name: zentra-user-service-redis-data-node-5
  zentra-user-service-redis-data-node-6:
    name: zentra-user-service-redis-data-node-6

networks:
  zentra-network:
    name: zentra-network
    external: true
  zentra-user-service-network:
    name: zentra-user-service-network
    driver: bridge
  zentra-user-service-redis-network:
    name: zentra-user-service-redis-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.48.0.0/16
